package constants

const val PBKDF2_ITERATION_COUNT = 1000
const val PBKDF2_KEY_LENGTH = 128

const val SCRYPT_COST_PARAM = 2048
const val SCRYPT_BLOCKSIZE = 8
const val SCRYPT_PARALLELIZATION_PARAM = 1
